name: MapCreator
main: dev.dementisimus.mapcreator.MapCreatorPlugin
author: dementisimus
version: ${project.version}
website: dementisimus.dev
depend: [ CoreAPI ]
softdepend: [ CoreAPIDependencies, SlimeWorldManager ]
api-version: 1.17

commands:
  mapcreator:
  mc:
