name: MapCreator
main: dev.dementisimus.mapcreator.MapCreator
author: dementisimus
version: ${project.version}
website: dementisimus.dev
softdepend: [ CoreAPI, CoreAPIDependencies ]
api-version: 1.17

commands:
  mapcreator:
  mc:
