name: Bug Report
description: File a bug report
labels: ["bug"]
assignees:
- dementisimus

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Tell us what should happen
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Tell us what happens instead of the expected behavior
    validations:
      required: true

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Describe the bug detailed
      value: see Expected & Current Behavior above
    validations:
      required: false

  - type: textarea
    id: stacktraces-log-output
    attributes:
      label: Stacktraces / Log output
      description: If you encountered any stacktraces, or you simply want to add some log
      render: shell
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java version
      description: What version of Java are you using ('java -version' output) ?
    validations:
      required: true

  - type: dropdown
    id: database
    attributes:
      label: Database
      description: What database are you using?
      options:
          - 'MongoDB'
          - 'MariaDB (MySQL)'
          - 'SQLite'
    validations:
      required: true

  - type: input
    id: database-version
    attributes:
      label: Database version
      description: What version of the previously specified database are you using?
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you using ('/version' output)?
    validations:
      required: true

  - type: dropdown
    id: using-paper
    attributes:
      label: PaperMC
      description: Are you using PaperMC?
      options:
          - 'yes'
          - 'no'
    validations:
      required: true

  - type: input
    id: aswm-version
    attributes:
      label: ASWM version
      description: What version of ASWM (Advanced-Slime-World-Manager) are you using ('/about SlimeWorldManager' version output)?
    validations:
      required: true

  - type: input
    id: mapcreator-version
    attributes:
      label: MapCreator version
      description: What version of MapCreator are you using ('/about MapCreator' version output)?
    validations:
      required: true
