name: build
on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
      - name: clear caches
        run: git rm --cached /home/runner/work/MapCreator/MapCreator
