name: build
on: [ push ]

jobs:
  build:
  
    env: 
      id: MapCreator
      version: 1.4.0
      file: ${{ env.id }}-${{ env.version }}.jar
  
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
          
      - name: setup-jdk-16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          
      - name: build
        run: mvn -U clean package --file pom.xml
        
      - name: cache
        uses: actions/cache@v2
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-maven-
            
      - name: deploy
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
            local: ./${{ env.file }}
            remote: /home/${{ env.file }}
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            privateKey: ${{ secrets.PRIVATE_KEY}}
