name: build
on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
          
      - name: setup-jdk-16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          
      - name: build
        run: mvn -U clean package --file pom.xml
        
      - name: cache
        uses: actions/cache@v2
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-maven-
            
      - name: deploy
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
