name: build
on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
          
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          
      - name: clean package
        run: mvn -U clean package --file pom.xml
