name: build
on: [ push, workflow_dispatch ]

env: 
  name: MapCreator
  id: mapcreator
  version: 1.4.0
  jar: MapCreator-1.4.0.jar
  pom: MapCreator-1.4.0.pom
  stage: development

jobs:
  build:  
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
          
      - name: setup-jdk-16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          
      - name: cache
        uses: actions/cache@v2
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-maven-
          
      - name: build
        run: mvn -U clean package --file pom.xml
            
      - name: pre-deploy
        run: |
          mkdir ./to-deploy
          cp ./target/${{ env.jar }} ./to-deploy/${{ env.jar }}
          cp ./pom.xml ./to-deploy/${{ env.pom }}
            
      - name: deploy
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
            local: ./to-deploy
            remote: /home/repo-deployment/repository/repositories/${{ env.stage }}/dev/dementisimus/${{ env.id }}/${{ env.name }}/${{ env.version }}/
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            privateKey: ${{ secrets.PRIVATE_KEY}}
            passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
